SectionVerb {
	# $ amixer -c rockchiprk809co contents | grep -A 12 "Playback Path"
	EnableSequence [
		cset "name='Playback Path' HP"
	]

	DisableSequence [
		cset "name='Playback Path' OFF"
	]

	Value {
		TQ "HiFi"
		ControlDevice "hw:${CardNumber}"
	}
}

SectionDevice."Headphones" {
        Comment "Headphones"

        Value {
                PlaybackPriority "100"
                PlaybackPCM "hw:${CardNumber},0"
                PlaybackChannels "2"

                JackControl "Headphone Jack"

                DeviceType "Headphones"
                Direction "playback"
        }
}

