#!/bin/sh

set -e

. /usr/share/odroid-base/library.sh

alsa_setup() {
	case "$(odroid_model_simple)" in
		odroidn2 | odroidn2_plus)
			major=$(uname -r | cut -d'.' -f1)
			[ "x$major" = "x4" ] && return

			amixer -q sset 'FRDDR_A SINK 1 SEL' 'OUT 1' || true
			amixer -q sset 'FRDDR_A SRC 1 EN' 'on' || true
			amixer -q sset 'TDMOUT_B SRC SEL' 'IN 0' || true
			amixer -q sset 'TOHDMITX I2S SRC' 'I2S B' || true
			amixer -q sset 'TOHDMITX' 'on' || true

			amixer -q sset 'FRDDR_B SINK 1 SEL' 'OUT 2' || true
			amixer -q sset 'FRDDR_B SRC 1 EN' 'on' || true
			amixer -q sset 'TDMOUT_C SRC SEL' 'IN 1' || true
			amixer -q sset 'TOACODEC SRC' 'I2S C' || true
			amixer -q sset 'TOACODEC OUT EN' 'on' || true
			amixer -q sset 'TOACODEC Lane Select' '0' || true
			amixer -q sset 'ACODEC' '255'

			amixer -q sset 'FRDDR_C SINK 1 SEL' 'OUT 3' || true
			amixer -q sset 'FRDDR_C SRC 1 EN' 'on' || true
			amixer -q sset 'SPDIFOUT SRC SEL' 'IN 2' || true
			;;

		odroidn2l)
			major=$(uname -r | cut -d'.' -f1)
			[ "x$major" = "x4" ] && return

			amixer -q sset 'FRDDR_A SINK 1 SEL' 'OUT 1' || true
			amixer -q sset 'FRDDR_A SRC 1 EN' 'on' || true
			amixer -q sset 'TDMOUT_B SRC SEL' 'IN 0' || true
			amixer -q sset 'TOHDMITX I2S SRC' 'I2S B' || true
			amixer -q sset 'TOHDMITX' 'on' || true

			amixer -q sset 'FRDDR_B SINK 1 SEL' 'OUT 2' || true
			amixer -q sset 'FRDDR_B SRC 1 EN' 'on' || true
			amixer -q sset 'TDMOUT_C SRC SEL' 'IN 1' || true
			amixer -q sset 'TOACODEC SRC' 'I2S C' || true
			amixer -q sset 'TOACODEC OUT EN' 'on' || true
			amixer -q sset 'TOACODEC Lane Select' '0' || true
			amixer -q sset 'ACODEC' '255'
			;;

		odroidc4 | odroidhc4)
			major=$(uname -r | cut -d'.' -f1)
			[ "x$major" = "x4" ] && return

			amixer -q sset 'FRDDR_A SINK 1 SEL' 'OUT 1' || true
			amixer -q sset 'FRDDR_A SRC 1 EN' 'on' || true
			amixer -q sset 'TDMOUT_B SRC SEL' 'IN 0' || true
			amixer -q sset 'TOHDMITX I2S SRC' 'I2S B' || true
			amixer -q sset 'TOHDMITX' 'on' || true
			;;

		odroidc5)
			major=$(uname -r | cut -d'.' -f1)
			[ "x$major" = "x4" ] && return

			amixer -q sset 'HDMITX Audio Source Select' 'Tdm_B' || true
			amixer -q sset 'AMP DAC Digital' '254' || true
			;;
		*)
			;;
	esac
}

pulseaudio_setup() {
	[ -f "${ODROID_PA_CONFIG}" ] && return

	mkdir -p "$(dirname ${ODROID_PA_CONFIG})"

	case "$(odroid_model_simple)" in
		odroidc5)
			cat>"${ODROID_PA_CONFIG}"<<__EOF
			load-module module-alsa-sink device=hw:0,1 sink_name=spdif2hdmi sink_properties=device.description=HDMI-SPDIF
			load-module module-alsa-sink device=hw:0,2 sink_name=line sink_properties=device.description=Line-out
			load-module module-alsa-sink device=hw:0,3 sink_name=spdif sink_properties=device.description=SPDIF-out
			set-default-sink alsa_output.platform-auge_sound.stereo-fallback
__EOF
			;;
		odroidm1 | odroidm1s)
			cat>"${ODROID_PA_CONFIG}"<<__EOF
			set-card-profile 0 output:hdmi-stereo
			set-default-sink alsa_output.platform-hdmi-sound.hdmi-stereo
__EOF
			;;
		odroidm2)
			cat>"${ODROID_PA_CONFIG}"<<__EOF
			set-card-profile 0 output:hdmi-stereo
			set-default-sink alsa_output.platform-hdmi0-sound.hdmi-stereo
__EOF
			;;
		*)
			cat>"${ODROID_PA_CONFIG}"<<__EOF
			set-card-profile 0 output:hdmi-stereo
__EOF
			;;
	esac

	if [ -f /usr/share/pulseaudio/alsa-mixer/paths/hdmi-output-0.conf ]; then
		sed -i "s/^priority =.*/priority = 100/g" \
			/usr/share/pulseaudio/alsa-mixer/paths/hdmi-output-0.conf
	fi
}
