#!/bin/sh

. /usr/share/odroid-alsa/functions

case "$(odroid_model_simple)"  in
	odroidc5)
		cat>/etc/modules-load.d/sound-amlogic.conf<<__EOF
amlogic-snd-codec-dummy
amlogic-snd-codec-t9015
__EOF
;;
esac

alsa_setup
alsa_ucm_setup
pulseaudio_setup
