monitor.alsa.rules = [
{
    matches = [
    {
        "device.nick" = "ODROID-C4"
        "media.class" = "Audio/Device"
    }
    {
        "device.nick" = "ODROID-HC4"
        "media.class" = "Audio/Device"
    }
    {
        "device.nick" = "ODROID-N2"
        "media.class" = "Audio/Device"
    }
    {
        "device.nick" = "ODROID-N2L"
        "media.class" = "Audio/Device"
    }
    ]
        actions = {
            update-props = {
                "api.alsa.split-enable" = true
                "api.alsa.use-acp" = false
                "api.alsa.use-ucm" = true
                "device.description" = "HDMI Digital Audio"
                "device.product.name" = "ODROID-C4 HDMI Audio"
            }
        }
}
{
    matches = [
    {
        "node.name" = "alsa_output.platform-sound.playback.0.0"
        "node.nick" = "ODROID-C4"
    }
    {
        "node.name" = "alsa_output.platform-sound.playback.0.0"
        "node.nick" = "ODROID-HC4"
    }
    {
        "node.name" = "alsa_output.platform-sound.playback.0.0"
        "node.nick" = "ODROID-N2"
    }
    {
        "node.name" = "alsa_output.platform-sound.playback.0.0"
        "node.nick" = "ODROID-N2L"
    }
    ]
        actions = {
            update-props = {
                "audio.channels"  = "2"
                "audio.position"  = "[ FL, FR ]"
                "node.description" = "HDMI Digital Audio (Stereo)"
            }
        }
}
{
    matches = [
    {
        "node.name" = "alsa_output.platform-sound.playback.1.0"
        "node.nick" = "ODROID-N2"
    }
    ]
        actions = {
            update-props = {
                "audio.channels"  = "2"
                "audio.position"  = "[ FL, FR ]"
                "node.description" = "Headphone"
            }
        }
}
]
// vim: ts=4 sw=4 et
