SectionDevice."HDMI" {
	Comment "HDMI Output"

	Value {
		PlaybackPriority 200
		PlaybackPCM "hw:${CardNumber},0"
		PlaybackChannels 2

		DeviceType "HDMI"
	}
}

SectionDevice."Headphones" {
	Comment "Earphone Jack"

	Value {
		PlaybackPriority 100
		PlaybackPCM "hw:${CardNumber},1"
		PlaybackChannels 2

		DeviceType "Headphones"
	}
}
