# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2022 Hardkernel Co., Ltd.

<confdir:pcm/front.conf>

ODROID-M1-FRONT.pcm.front.0 {
        @args [ CARD ]
        @args.CARD {
		type string
	}
	type hooks
	slave.pcm {
		type hw
		card $CARD
		device 0
	}
	hooks.0 {
		type ctl_elems
		hook_args [
			{ name "Playback Path" value 6 }
			# 0: OFF 1: RCV 2: SPK 3: HP 4: HP_NO_MIC 5: BT
			# 6: SPK_HP 7: RING_SPK 8: RING_HP 9: RING_HP_NO
		]
	}
}
