# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2020-present Team LibreELEC (https://libreelec.tv)
# Copyright (C) 2022 Hardkernel Co., Ltd.

<confdir:pcm/hdmi.conf>

SM1-ODROID-C4.pcm.hdmi.0 {
        @args [ CARD AES0 AES1 AES2 AES3 ]
        @args.CARD { type string }
        @args.AES0 { type integer }
        @args.AES1 { type integer }
        @args.AES2 { type integer }
        @args.AES3 { type integer }
        type hooks
        slave.pcm {
                type hw
                card $CARD
                device 0
                subdevice 0
        }
        hooks.0 {
                type ctl_elems
                hook_args [
                        {
                                interface MIXER
                                name "IEC958 Playback Default"
                                lock true
                                preserve true
                                optional true
                                value [ $AES0 $AES1 $AES2 $AES3 ]
                        }
			{ name "FRDDR_A SINK 1 SEL" value "OUT 1" }
			# 0: 'OUT 0' 1: 'OUT 1' 2: 'OUT 2' 3: 'OUT 3'
			# 4: 'OUT 4' 5: 'OUT 5' 6: 'OUT 6' 7: 'OUT 7'
			{ name "FRDDR_A SRC 1 EN" value "on" }
			{ name "TDMOUT_B SRC SEL" value "IN 0" }
			# 0: 'IN 0' 1: 'IN 1' 2: 'IN 2' 3: 'IN 3'
			# 4: 'IN 4'
			{ name "TOHDMITX I2S SRC" value "I2S B" }
			# 0: 'I2S A' 1: 'I2S B' 2: 'I2S C'
			{ name "TOHDMITX" value "on" }
			# 0: off 1: on
                ]
        }
        hint.device 0
}
